volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:14
    env_file: ../backend/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    env_file: ../backend/.env
    container_name: foodgram-back
    build: ../backend/
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db
  frontend:
    env_file: ../backend/.env
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - static:/static
  nginx:
    env_file: ../backend/.env
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/static
      - media:/media
    depends_on:
      - backend
